// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Q0HCbPYZceRCzwk8QBEoHD0Cp_XcYz0',
    appId: '1:861292911235:web:442bd967f054a90ad3d9b6',
    messagingSenderId: '861292911235',
    projectId: 'fitness-tracker-18777',
    authDomain: 'fitness-tracker-18777.firebaseapp.com',
    storageBucket: 'fitness-tracker-18777.firebasestorage.app',
    measurementId: 'G-K00NZT0W0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-C970hX5GbnavasJ4g2yUEQyQlMiKFYk',
    appId: '1:861292911235:android:8ca86e2b60b357c5d3d9b6',
    messagingSenderId: '861292911235',
    projectId: 'fitness-tracker-18777',
    storageBucket: 'fitness-tracker-18777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRIfRowqDn2ibBtQhMF-JYxUg6Rb1Jg44',
    appId: '1:861292911235:ios:bac47ae50f84f463d3d9b6',
    messagingSenderId: '861292911235',
    projectId: 'fitness-tracker-18777',
    storageBucket: 'fitness-tracker-18777.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRIfRowqDn2ibBtQhMF-JYxUg6Rb1Jg44',
    appId: '1:861292911235:ios:bac47ae50f84f463d3d9b6',
    messagingSenderId: '861292911235',
    projectId: 'fitness-tracker-18777',
    storageBucket: 'fitness-tracker-18777.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Q0HCbPYZceRCzwk8QBEoHD0Cp_XcYz0',
    appId: '1:861292911235:web:509b26a4dfe70ae5d3d9b6',
    messagingSenderId: '861292911235',
    projectId: 'fitness-tracker-18777',
    authDomain: 'fitness-tracker-18777.firebaseapp.com',
    storageBucket: 'fitness-tracker-18777.firebasestorage.app',
    measurementId: 'G-FHDMFQ5R97',
  );
}
